name: Terminal
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-python@v3
    - run: pip3 install requests
    
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
